name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta todos los días a medianoche
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: "languages, hours, days" # muestra solo lenguajes, horas y días
          LANG_COUNT: 1                    # número de lenguajes que se muestran
          SHOW_TIME: true
          SHOW_TOTAL: false                # oculta total de horas
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: YAML JSON TOML # ignora estos lenguajes si aparecen
